### ISSUE TITLE
can't make it

### ISSUE THREAD

**Issue by henrykey** [crotoc/luci-app-v2ray#1]
最后一步了，做make时出问题：
make[1]: *** No rule to make target 'package/luci-app-v2ray-pro/down'.  Stop.
我该如何往下？
谢谢！

**Comment by crotoc** [comment]
你可不可以吧package/luci-v2ray-pro下面文件ls下，我这里这个目录下面并没有这个down文件

**Comment by henrykey** [comment]
luasrc	Makefile  po  root

**Comment by henrykey** [comment]
下面时ls的文件<br>luasrc	Makefile  po  root
<b>

**Comment by henrykey** [comment]
从你的说明里抄的编译命令<br>make package/luci-app-v2ray-pro/{down,compile} -j20<br>除了核我选的多以外，都没变

**Comment by henrykey** [comment]
make package/luci-app-v2ray-pro/{clean,compile} -j8这个命令好像可以正常进行，还没完

**Comment by crotoc** [comment]
应该是make down compile这个有问题，你看看make clean compile行不行

**Comment by henrykey** [comment]
可以了，谢谢1

**Comment by crotoc** [comment]
那就好

**Comment by henrykey** [comment]
再次感谢！多问一个应用的问题，第三栏的servers setting是什么意思？备用服务器吗？server出问题就使用这个？谢谢！

**Comment by crotoc** [comment]
这个我也不知道，没用过这一栏。你去看看l大的里面有没有说明
