### ISSUE TITLE
能在release里面放build好的package吗？

### ISSUE THREAD

**Issue by nickleefly** [crotoc/luci-app-v2ray#2]

**Comment by crotoc** [comment]
我github用的不熟，我试试。你需要哪个核心的

**Comment by crotoc** [comment]
你需要那个核心的？

**Comment by nickleefly** [comment]
r7800的

**Comment by crotoc** [comment]
好的！

**Comment by nickleefly** [comment]
可以看这里https://help.github.com/en/articles/creating-releases

**Comment by crotoc** [comment]
传上去了，你看看

**Comment by nickleefly** [comment]
谢谢，晚上回家试试

**Comment by nickleefly** [comment]
安装不上去
```
Collected errors:
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/hotplug.d/ntp/25-dnsmasqsec
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /etc/init.d/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/acl.d/dnsmasq_acl.json
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-v2ray-pro
```

**Comment by crotoc** [comment]
先删除机器的dnsmasq然后再装dnsmasq-full

**Comment by nickleefly** [comment]
然后网络就挂了

**Comment by crotoc** [comment]
ssh重新连接应该能上吧？

**Comment by nickleefly** [comment]
remove掉dnsmasq 就不能上了，我又重新装回去了，v2ray路由上要用5353端口吗？

**Comment by crotoc** [comment]
重装上dnsmasq-full，这个包和dnsmasq是一样的，但是包含了一些其他需要的功能。v2ray路由上面用的是7070端口，你不需要做什么，/etc/init.d/v2raypro会自动的添加防火墙

**Comment by nickleefly** [comment]
好的，我明天再试试吧

**Comment by nickleefly** [comment]
你装完的luci v2ray方便截个图吗

**Comment by crotoc** [comment]
你是需要看luci界面的样子么？

**Comment by crotoc** [comment]
![image](https://user-images.githubusercontent.com/12446554/59363161-578bc080-8cfa-11e9-8e64-f28196ee12b9.png)

**Comment by nickleefly** [comment]
谢谢
我直接`v2ray -config /etc/v2ray/config.json` 启动

```
$ dig google.com

; <<>> DiG 9.9.7-P3 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 64121
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		31	IN	A	172.217.161.142

;; Query time: 3 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Jun 12 23:13:07 CST 2019
;; MSG SIZE  rcvd: 55
```
 但是访问不了谷歌

**Comment by nickleefly** [comment]
装你这个 还是需要ChinaDNS吧？

**Comment by crotoc** [comment]
直接这样启动不行，因为启动了这个服务只代表你开始运行代理了。但是需要做的是将你需要的流量direct到这个进程监听的端口，这样需要一系列的iptables的命令。启动v2ray的主程序是这个/etc/init.d/v2raypro，你打开看看就有点感觉了。所以你必须能够安装好luci，然后打开才有效。不然的话需要自己手动添加iptables才可以。

**Comment by nickleefly** [comment]
了解了，谢谢，我明天再试一下 👍

**Comment by crotoc** [comment]
我仔细描述一下包的过程：比如从你的手机连接google，这个包发到路由器，路由器的防火墙（iptables起作用）检查你的ipset里面的对应国外域名的地址和ip，然后发现匹配，将这个包转发到路由器的7070端口，然后v2ray主程序监听到这个包，就将这个包转发给代理服务器。然后代理服务器查询之后返回结果给v2ray。这样构成一个回路。你现在在本地打开了v2ray的服务，但是没有防火墙将需要的包转给v2ray，这条线路就断了。

**Comment by crotoc** [comment]
你自己的config开的什么端口你应该知道吧，你可以简单测试一下：

**Comment by nickleefly** [comment]
知道的，手机上已经能联通了

**Comment by nickleefly** [comment]
电脑上怎么测试通不通？

**Comment by crotoc** [comment]
你的手机上可以连google但是电脑不行？

**Comment by nickleefly** [comment]
电脑没加iptables规则呢， 用这个Luci v2ray还需要搞iptables规则吗？

**Comment by nickleefly** [comment]
这个包也会被gfw DPI的吧？

**Comment by crotoc** [comment]
不需要，这个luci v2ray里面已经将iptables规则加进去了，每次启动，都会加入一堆规则，然后关闭的时候自动删除。
可以按照下面的方式的测试一下，假设你需要测试的机器内网ip地址是192.168.1.100，ssh到你的路由器，使用：
netstat -nlp | grep v2ray
看看里面有没有一个v2ray是否已经开始监听你的某个端口。如果有表示v2ray成功启动。

然后自己在openwrt的luci界面里面nework->firewall->custome中加入下面一条：
iptables -t nat -I PREROUTING -s 192.168.1.100 -p tcp  -j REDIRECT --to-ports $V2RAY_REDIR_PORT
修改其中的192.168.1.100 成你的某一台需要连接机器的ip；修改其中的$V2RAY_REDIR_PORT到你的v2ray的监听端口，就是上面一行查出来的端口，这样相当于把你某台机器的tcp流量全部转给服务器了。上面那条的意思是说将进入路由器最先进入prerouting链中的包，来源是192.168.1.100，协议是tcp，转发到另一个端口。再看看能不能连接ip.cn。
然后需要删除的时候使用
iptables -t nat -L PREROUTING --line-numbers
![image](https://user-images.githubusercontent.com/12446554/59366149-70e33b80-8cff-11e9-9ec2-637d0f116578.png)
找到刚刚加的那一条的数字，使用下面命令删除：
iptables -t nat -L PREROUTING -D YOUR_NUMBER

然后输入下面命令确认一下：
iptables -t nat -L PREROUTING --line-numbers

关于DNS污染的问题我研究的少，所以了解不多。这个里面使用了pdnsd进行了中转，可以通过luci里面打开：
![image](https://user-images.githubusercontent.com/12446554/59367103-11862b00-8d01-11e9-99e3-769ec317d1be.png)

最后就是如果要测试不需要连接google，用你的测试的客户端上ip.cn，如果ip变成你v2ray服务器ip了就成功了。这样即使dns收到了污染你也知道是否成功

**Comment by crotoc** [comment]
DPI啥意思

**Comment by crotoc** [comment]
> 电脑没加iptables规则呢， 用这个Luci v2ray还需要搞iptables规则吗？

所有的iptables规则都是在路由器上加的，和客户端（电脑、手机）都没有任何关系。手机上如果安装v2ray的专用的客户端，那里面的包的转发又是另外一个故事了。

**Comment by nickleefly** [comment]
https://en.m.wikipedia.org/wiki/Deep_packet_inspection

**Comment by nickleefly** [comment]
Luci就是方便管理，iptables还是要加的对吧

**Comment by crotoc** [comment]
> https://en.m.wikipedia.org/wiki/Deep_packet_inspection

肯定会。你的路由器发出去的包到海外服务器的这个过程就会被查看。v2ray服务器如果只是使用kcp混淆啥的也是有可能被查出来。所以最好的情况是v2ray的服务器使用tls+websocket+CDN，这样的话你的流量其实就是变成了访问一个网站的流量，而且内容是https加密的，这样会好一些。但是你如果和国外一个服务器的流量很大，还是会被看着的。所以找个稳定的机场可能比较重要。因为很多机场只是某些网站的副业，他们的网站确实有很多流量，这样你的流量就不算什么了。

**Comment by crotoc** [comment]
> Luci就是方便管理，iptables还是要加的对吧

这个luci集成了家iptables的功能。无论干啥iptables都必须加，不然你的规则就没有起作用了。你的目标应该是透明代理，就是国内流量直连，科学上网通过代理，这样的话必须由ipset匹配请求的ip然后使用iptables转发需要的流量。

**Comment by nickleefly** [comment]
搞了 websocket tls cloudflare了

**Comment by crotoc** [comment]
> 搞了 websocket tls cloudflare了

厉害

**Comment by nickleefly** [comment]
装了你这几个ipk 之后dns 解析出问题
